name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: killedkenny/sakila

      - name: Build and push PG Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: pg_image
          file: ./pg_image/Dockerfile
          push: true
          tags: killedkenny/sakila:postgres
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push MariaDB Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: mariadb_image
          file: ./mariadb_image/Dockerfile
          push: true
          tags: killedkenny/sakila:mariadb
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push MySQL Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: mysql_image
          file: ./mysql_image/Dockerfile
          push: true
          tags: killedkenny/sakila:mysql
          labels: ${{ steps.meta.outputs.labels }}

      #- name: Build and push db2 Docker image
      #  uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      #  with:
      #    context: db2_image
      #    file: ./db2_image/Dockerfile
      #    push: true
      #    tags: killedkenny/sakila:db2
      #    labels: ${{ steps.meta.outputs.labels }}